name: Publish docs

on:
  workflow_dispatch:
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run typedoc:generate
      - run: sed -ie 's/\(Exports\#.*\)-1/\1/g' wiki/Exports.md
        # Additional steps to generate documentation in "wiki" directory
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: 'wiki'
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
